### PR TITLE
Add callback as second parameter

### PR DESCRIPTION
**Pull request by saamo**
Acquit tries to find matches in each `it` block's code field with provided pattern and if it finds one, it will run a callback on that match and save the result into block's `matches` field (you can have more matches of course).

The code below generates [API Blueprint](https://apiblueprint.org) and in particular it _loads_ request/response JSON from a file.

```js
var acquit = require('../acquit');
var fs = require('fs');

module.exports = function(content) {
  var cb = function(file) {
    if (file) {
      return fs.readFileSync(file).toString();
    }
  };

  // parse and load requests and responses
  var groups = acquit.parse(content, /(?:reqFile|resFile) = '(.*)'/g, cb);

  var doc = '';

  // groups
  for (var i in groups) {
    ...
    // resources
    for (var j in resources) {
      ...
      // actions
      for (var k in actions) {
        ...
        // request and response payload
        if ('matches' in test) {
          doc += formatPayload(test.matches[0], '+ Request (application/json)');
        }
      }
    }
  }

  return doc;
};
```

Example test:

```js
describe('Users', function() {
  describe('Users [/users/]', function() {
    describe('Create a user [POST]', function() {
      it('Returns user if user is created successfully.', function(done) {
        var reqFile = 'tests/user/createUserReq.json';
        api.post('/users/')
          .send(jsonfile.readFileSync(reqFile))
          .expect(200)
          .expect('Content-Type', /json/)
          .end(done);
      })
    });
  });
});
```

### CODE REVIEW

**Comment by vkarpov15** [comment]
Hmm I'd like to see a more general way of doing a visitor pattern - just running a regex match against the block's code seems a little limited. IMO would be better to just define a general way to say 'call this function for each `it()`' or something like that and defer the particulars to the user. Would that be helpful?

**Comment by saamo** [comment]
That would be definitely a better approach in terms of general usage. I'll get back to you with that.

**Comment by saamo** [comment]
Now it takes a callback as second parameter, invokes it for each `code` block and saves return value into a field named `cb`.

**Comment by vkarpov15** [comment]
I like this better, but I think the ideal approach would be the 2nd parameter to `.parse()` is a callback that takes a block and modifies it however it wants. So the `cb()` in your test would look like this:

```javascript
var cb = function(block) {
  if (block.code) {
    block.code = 'return value from callback';
  }
};
```

**Comment by saamo** [comment]
How about this?

**Comment by vkarpov15** [comment]
lgtm, thanks!

**Comment by saamo** [comment]
Thank you! When are you going to publish to NPM?

**Comment by vkarpov15** [comment]
Tomorrow

**Pull request merged**
